apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270leviservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270leviservice
  template:
    metadata:
      name: cit270leviservice
      labels: 
        app: cit270leviservice
    spec:
      containers:
      - name: cit270leviservice
        image: gcr.io/cit-270-kubernetes-379820/levi-api
        volumeMounts:
        - name: ssl
          mountPath: "/etc/letsencrypt/live/levichudleigh.cit270.com/"
        command: ["npm"]
        args: ["run","start"]
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret:
          secretName: levicerts